### PR TITLE
Update to pytest-3.0.6

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@jakirkham @ocefpaf any idea why AppVeyor has not started?

**Comment by goanpeca** [comment]
@nicoddemus rate limit is up. You need to wait an hour (or actually less... ) like half an hour for it to reset. Then close and reopen the PR.

**Comment by nicoddemus** [comment]
@goanpeca thanks for the response!

**Comment by jakirkham** [comment]
Yeah, see issue ( https://github.com/conda-forge/conda-forge.github.io/issues/314 ). Thinking about adding another bot just for AppVeyor or moving everything else off the bot being used for AppVeyor. May require a bit of coordination to do the bot shuffle.

**Comment by nicoddemus** [comment]
Restarted the Travis build manually. 😓

**Pull request merged**
