### PR TITLE
Release 3.2.2

### PR DESCRIPTION
**Pull request by nicoddemus**
Also trying out the new `noarch` build.

### CODE REVIEW

**Comment by jakirkham** [comment]
Given the `noarch: python` package has some issues on Windows, should we pull it @nicoddemus?

**Comment by nicoddemus** [comment]
@marscher

> Is this still an issue? I'am relying on pytest-4 for Python-2.7 but can not install it because this pkg is not noarch.

I believe your issue is different, there's been no reports of problems with this pytest 4 on Windows. The problem in this issue is that we changed the package to `noarch`, but the recipe install some packages depending on platform (`colorama` for Windows), which is not supported by `noarch` packages.

Unless I'm misunderstanding something, please open a separate issue so we can sort this out. 👍

**Comment by nicoddemus** [comment]
@jakirkham 

Sorry I missed https://github.com/conda-forge/pytest-feedstock/pull/23#issuecomment-330898235. Yes I'm OK with removing the package, although it might break if someone has a pin to that version on Linux.

**Comment by nicoddemus** [comment]
@jakirkham how do you pull a package? I might remember someone mentioning that we should use an `invalid` label?

https://anaconda.org/conda-forge/pytest/files?version=3.2.2

I don't see how one can create labels, I believe only @conda-forge-admin can do it?

**Pull request merged**
