### PR TITLE
Rebuild v4.0.2 for Python 3.8

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
Hi @hoechenberger,

I've changed the base to `4.0` so we don't conflict with the latest release. 👍 

Once this passes we can merge it.

**Comment by hoechenberger** [comment]
@nicoddemus This is great, I didn't know how to do this myself! Thank you! May I also add myself as a maintainer here to make future adjustments a little less work for you?

**Comment by nicoddemus** [comment]
> This is great, I didn't know how to do this myself! Thank you! May I also add myself as a maintainer here to make future adjustments a little less work for you?

Yeah only maintainers can create branches on the repository. Sure, go ahead to add yourself as maintainer. 👍 

Btw out of curiosity, why do you need pytest 4.0.X?

**Comment by hoechenberger** [comment]
> Sure, go ahead to add yourself as maintainer. 👍

 Great, thanks!

> Btw out of curiosity, why do you need pytest 4.0.X?

The [PsychoPy](https://github.com/psychopy/psychopy) test suite unfortunately does not (yet) work with `pytest` >4.0, which is one of the issues that's been keeping us from testing on Python 3.8 (`pytest` 4.0 is available from `conda-forge` for Python versions up to 3.7, but not 3.8) Ultimately, of course, the test suite needs to be updated.

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
@nicoddemus CI is all green now :)

**Comment by nicoddemus** [comment]
Thanks!

**Pull request merged**
