### PR TITLE
update to 3.0.2

### PR DESCRIPTION
**Pull request by ocefpaf**
```
3.0.2
=====

* Improve error message when passing non-string ids to ``pytest.mark.parametrize`` (`#1857`_).
  Thanks `@okken`_ for the report and `@nicoddemus`_ for the PR.

* Add ``buffer`` attribute to stdin stub class ``pytest.capture.DontReadFromInput``
  Thanks `@joguSD`_ for the PR.

* Fix ``UnicodeEncodeError`` when string comparison with unicode has failed. (`#1864`_)
  Thanks `@AiOO`_ for the PR.

* ``pytest_plugins`` is now handled correctly if defined as a string (as opposed as
  a sequence of strings) when modules are considered for assertion rewriting.
  Due to this bug, much more modules were being rewritten than necessary
  if a test suite uses ``pytest_plugins`` to load internal plugins (`#1888`_).
  Thanks `@jaraco`_ for the report and `@nicoddemus`_ for the PR (`#1891`_).

* Do not call tearDown and cleanups when running tests from
  ``unittest.TestCase`` subclasses with ``--pdb``
  enabled. This allows proper post mortem debugging for all applications
  which have significant logic in their tearDown machinery (`#1890`_). Thanks
  `@mbyt`_ for the PR.
  
* Fix use of deprecated ``getfuncargvalue`` method in the internal doctest plugin.
  Thanks `@ViviCoder`_ for the report (`#1898`_).

.. _@joguSD: https://github.com/joguSD
.. _@AiOO: https://github.com/AiOO
.. _@mbyt: https://github.com/mbyt
.. _@ViviCoder: https://github.com/ViviCoder

.. _#1857: https://github.com/pytest-dev/pytest/issues/1857
.. _#1864: https://github.com/pytest-dev/pytest/issues/1864
.. _#1888: https://github.com/pytest-dev/pytest/issues/1888
.. _#1891: https://github.com/pytest-dev/pytest/pull/1891
.. _#1890: https://github.com/pytest-dev/pytest/issues/1890
.. _#1898: https://github.com/pytest-dev/pytest/issues/1898
```

### CODE REVIEW

**Comment by nicoddemus** [comment]
Nice! :sunglasses: 

I was planning on doing this myself tonight, but thanks for stepping in.

**Comment by nicoddemus** [comment]
I noticed you re-rendered the supporting scripts... is that something maintainers are supposed to do?

**Comment by ocefpaf** [comment]
> I noticed you re-rendered the supporting scripts... is that something maintainers are supposed to do?

It is good practice but not mandatory. If the update passes without the re-rendering there is no need to do it. I only did it here b/c I know there would be a failure with it.

PS: The rerendering should be triggered automatically by the `bot` but the bots seem be on strike demanding better work rights. @pelson is dealing with them and hopefully we won't have a skynet situation.

**Comment by nicoddemus** [comment]
Great, thanks for the info! :+1:

**Pull request merged**
