### PR TITLE
Update to 6.0.0rc1

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge-admin, please restart ci

**Comment by TomAugspurger** [comment]
Was this supposed to go into the main conda-forge channel without any other labels? Typically release candidates get a label applied so that they're opt in (https://github.com/conda-forge/cfep/pull/3). But in the meantime, happy to be forced into testing the new release :)

**Comment by beckermr** [comment]
@conda-forge/pytest This PR should not have been merged into the main channel. We are going to mark this package as broken until you all can move it to a new channel with a new PR.

**Comment by ocefpaf** [comment]
> Was this supposed to go into the main conda-forge channel without any other labels? Typically release candidates get a label applied so that they're opt in ([conda-forge/cfep#3](https://github.com/conda-forge/cfep/pull/3)). But in the meantime, happy to be forced into testing the new release :)

We need a way to lint this to warn contributors and maintainers. Most people don't know about the CFEPs and they follow the PyPI model, just upload whatever and let the installed handle it. (Which is a feature we've been asking conda folks for a while.)

**Comment by nicoddemus** [comment]
Hey everyone,

Sorry about that, as @ocefpaf said I wasn't really aware we had a special policy for prereleases. Is that published somewhere other than that PR linked by @TomAugspurger? I will be happy to follow the proper procedure for prereleases in the future.

**Comment by ocefpaf** [comment]
@nicoddemus take a look at the pandas feedtock for an example. I can help you with the PR, just ping me if you need anything.

**Comment by nicoddemus** [comment]
Thanks @ocefpaf. 👍 

Taking a quick look the main difference I see is that there's a `dev` branch and the `recipe/conda_build_config.yml` file contains this directive:

```yaml
channel_targets:
  - conda-forge rc
```

Should I follow the same approach here? Anything missing?

Also if there's docs about this (I couldn't find anything on conda-forge.org/docs) I will be happy to follow it. 👍

**Comment by ocefpaf** [comment]
I don't think we ever made the CFEP into docs but it should be all in there: https://github.com/conda-forge/cfep/pull/3

PS: sorry, this is coming from someone that hates the fact that PEPs are becoming docs, and now I just did the same :-/

**Comment by beckermr** [comment]
Agreed we need docs. PRs welcome!

**Comment by nicoddemus** [comment]
Initial take: https://github.com/conda-forge/pytest-feedstock/pull/118

**Pull request merged**
