### PR TITLE
Update to 3.2.5

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by marscher** [comment]
thanks, 3.2.4 is unusable at the moment.

**Comment by marscher** [comment]
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (py 1.5.1 (/home/ubuntu/miniconda/conda-bld/pyemma-dev_1510759191340/_t_env/lib/python3.6/site-packages), Requirement.parse('py<1.5,>=1.4.33'), {'pytest'})!

**Comment by nicoddemus** [comment]
@marscher thanks for the heads up. As soon as CI passes we will merge it and this should be fixed.

**Comment by nicoddemus** [comment]
Well I don't think we really need for Travis to catch up, this actually fixes the previous requirements in 3.2.4.

**Pull request merged**
