### PR TITLE
Publish 6.0.0rc1 using the 'rc' label

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Hmmm something went wrong, the new files were still labelled as `main`:

image

🤔

**Comment by ocefpaf** [comment]
Did we re-render? I forgot...

**Comment by nicoddemus** [comment]
Ugh no. 😢 

Will mark it as broken again and restart the process.

**Comment by ocefpaf** [comment]
> Ugh no.

My fault. Bad reviewer!

> Will mark it as broken again and restart the process.

Thanks!

**Pull request merged**
