### PR TITLE
Apply Python 3.11 migration

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
Cross-compilation needs https://github.com/conda-forge/cross-python-feedstock/pull/56

**Comment by nicoddemus** [comment]
Thanks @chrisburr!

I see https://github.com/conda-forge/cross-python-feedstock/pull/56 was merged, do we need to trigger something here now?

**Comment by chrisburr** [comment]
Looks like there are some cross-compilation issues to work out for Python 3.11, I'll look into it.

**Comment by chrisburr** [comment]
@conda-forge/pytest This should be ready to go (feel free to merge the bot's PR instead if you'd prefer, I just used this package for testing the migrator manually).

**Comment by h-vetinari** [comment]
It would be good to merge this as soon as feasible because _a lot_ of feedstocks in the migration depend on this for building, but the migrator doesn't take that into account. This is because unfortunately the dependency graph for the migrator is built without test-only dependencies (which pytest almost always is), as that can lead to circularities (e.g. package A depending on B, and package B using A as a test-only dependency; this is not a build-level circularity, "just" on on recipe-level one).

**Pull request merged**
