### PR TITLE
Update feedstock to version 3.2.1

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks!

**Comment by ocefpaf** [comment]
CircleCI failed on master:

```
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /feedstock_root/build_artefacts/linux-64/pytest-3.2.1-py36_0.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes

anaconda_upload is not set.  Not uploading wheels: []
+ upload_or_check_non_existence /recipe_root conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Using Anaconda API: https://api.anaconda.org
[ERROR] 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 133, in add_release
    aserver_api.release(username, package_name, version)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 377, in release
    self._check_response(res)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.NotFound: ("release version=u'3.2.1' does not exist", 404)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 88, in main
    description=__doc__, version=version)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 242, in main
    args=args)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 180, in upload_package
    add_release(aserver_api, args, username, package_name, version, release_attrs)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 138, in add_release
    create_release(aserver_api, username, package_name, version, release_attrs)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/commands/upload.py", line 42, in create_release
    aserver_api.add_release(username, package_name, version, [], announce, release_attrs)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 417, in add_release
    self._check_response(res)
  File "/opt/conda/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.Unauthorized: ('Authorization token is no longer valid', 401)
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 122, in <module>
    main()
  File "/opt/conda/bin/upload_or_check_non_existence", line 111, in main
    upload(cli, meta, owner, channel)
  File "/opt/conda/bin/upload_or_check_non_existence", line 62, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/feedstock_root/build_artefacts/linux-64/pytest-3.2.1-py36_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
+ exit 1
Exited with code 1
```

My guess is that all feedstocks are suffering from that :unamused: 

(just found this one first b/c I needed this version)

**Comment by nicoddemus** [comment]
@ocefpaf do you have any follow up on that?

**Comment by ocefpaf** [comment]
Nope. I just woke up and I started looking into it. Hopefully we can fix it today.

**Comment by nicoddemus** [comment]
Great, thanks! Please let me know once you have more info.

Btw,

> (just found this one first b/c I needed this version)

Out of curiosity, you need this because of pytest-dev/pytest#2644?

**Pull request merged**
